## Play Tennis Weather Prediction 
#### We will predict if weather is good to play tennis or not

In [1]:
# importing required libraries

import pandas as pd
import numpy as np

In [2]:
# let's import the csv data using pandas

df = pd.read_csv(r'playTennisWeatherDataSet.csv') # it will return as a data frame
print(type(df))

<class 'pandas.core.frame.DataFrame'>

In [3]:
# Let's print the data
df

     Outlook Temperature Humidity    Wind Play Tennis
0      Sunny         Hot     High   Weak           No
1      Sunny         Hot     High  Strong          No
2   Overcast         Hot     High   Weak          Yes
3       Rain        Mild     High   Weak          Yes
4       Rain        Cool   Normal   Weak          Yes
5       Rain        Cool   Normal  Strong          No
6   Overcast        Cool   Normal  Strong         Yes
7      Sunny        Mild     High   Weak           No
8      Sunny        Cool   Normal   Weak          Yes
9       Rain        Mild   Normal   Weak          Yes
10     Sunny        Mild   Normal  Strong         Yes
11  Overcast        Mild     High  Strong         Yes
12  Overcast         Hot   Normal   Weak          Yes
13      Rain        Mild     High  Strong          No

#### This is classification issue as we have to only find Play Tennis as Yes or No. Hence, we have to convert all categorical variable into numerical variable such that our model can work better

In [4]:
# Let's import the required library to do this task

from sklearn.preprocessing import LabelEncoder

# creating an object of encoder

labelEncoder = LabelEncoder()

In [5]:
# Now, let's convet each categorical variable which are present in the dataset/dataframe

df['Outlook'] = labelEncoder.fit_transform(df['Outlook'])
df['Temperature'] = labelEncoder.fit_transform(df['Temperature'])
df['Humidity'] = labelEncoder.fit_transform(df['Humidity'])
df['Wind'] = labelEncoder.fit_transform(df['Wind'])
df['Play Tennis'] = labelEncoder.fit_transform(df['Play Tennis'])

In [6]:
# Now Let's have a look how data is looking 
df

    Outlook  Temperature  Humidity  Wind  Play Tennis
0         2            1         0     1            0
1         2            1         0     0            0
2         0            1         0     1            1
3         1            2         0     1            1
4         1            0         1     1            1
5         1            0         1     0            0
6         0            0         1     0            1
7         2            2         0     1            0
8         2            0         1     1            1
9         1            2         1     1            1
10        2            2         1     0            1
11        0            2         0     0            1
12        0            1         1     1            1
13        1            2         0     0            0

##### Great!  everything is now in numerical variable

In [7]:
# Let's see what is a uniqueness in the target variable means, how may unique values are there. 
# Here it will be only two, as prediction was Play Yes or No

df['Play Tennis'].unique()

array([0, 1])

#### Feature and Target Variables

In [8]:
feature = ['Outlook','Temperature','Humidity','Wind']
target = ['Play Tennis']

In [9]:
df[feature]

    Outlook  Temperature  Humidity  Wind
0         2            1         0     1
1         2            1         0     0
2         0            1         0     1
3         1            2         0     1
4         1            0         1     1
5         1            0         1     0
6         0            0         1     0
7         2            2         0     1
8         2            0         1     1
9         1            2         1     1
10        2            2         1     0
11        0            2         0     0
12        0            1         1     1
13        1            2         0     0

In [18]:
df[target]

    Play Tennis
0             0
1             0
2             1
3             1
4             1
5             0
6             1
7             0
8             1
9             1
10            1
11            1
12            1
13            0

### Naive Bayes Classifier - Model Building

#### Train and Test Split the data

In [19]:
# Let's import the required library
from sklearn.model_selection import train_test_split

feature_train, feature_test, target_train, target_test = train_test_split(df[feature],df[target])

#### Use the Algo for Model 
##### Naive bayes has three approaches
###### 1. Bernoulli:  Mainly use when we work with binary 
###### 2. Multinominal
###### 3. Gausian

In [20]:
feature_train

    Outlook  Temperature  Humidity  Wind
11        0            2         0     0
9         1            2         1     1
10        2            2         1     0
1         2            1         0     0
2         0            1         0     1
0         2            1         0     1
6         0            0         1     0
8         2            0         1     1
13        1            2         0     0
12        0            1         1     1

In [21]:
feature_test

   Outlook  Temperature  Humidity  Wind
5        1            0         1     0
4        1            0         1     1
7        2            2         0     1
3        1            2         0     1

In [22]:
# Let's import model algo

from sklearn.naive_bayes import MultinomialNB


model = MultinomialNB(alpha=5)


# Fit the model with train data 
model.fit(feature_train, target_train)

# Now let's make the prediction with test data
pred = model.predict(feature_test)
pred

d:\ProjectDesk\gh-iamatulkumar-ya\data-science\.venv\Lib\site-packages\sklearn\utils\validation.py:1406: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

array([1, 1, 1, 1])

##### Accuarcy of the Model

In [28]:
# To calcualte the accuracy of the model we havet to import the required library

from sklearn.metrics import accuracy_score, f1_score, confusion_matrix


accuracy = accuracy_score(target_test, pred)
accuracy

0.5

In [27]:
f1_score(target_test, pred)

0.6666666666666666

In [29]:
confusion_matrix(target_test, pred)

array([[0, 2],
       [0, 2]])

##### Make the Prediction - Test

In [24]:
input1 = [0,1,0,1]
print(model.predict([input1]))

[1]

d:\ProjectDesk\gh-iamatulkumar-ya\data-science\.venv\Lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but MultinomialNB was fitted with feature names
  warnings.warn(

In [16]:
input2 = [2,1,0,1]
print(model.predict([input2]))

[1]

d:\ProjectDesk\gh-iamatulkumar-ya\data-science\.venv\Lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but MultinomialNB was fitted with feature names
  warnings.warn(